# .github\workflows\playwright-2.yml
name: Playwright Tests 2
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm --prefix ./playwright ci
    - name: Install Playwright Browsers
      
      run: (cd playwright && npx playwright install --with-deps && cd -)
    - name: Run Playwright tests
      run: (cd playwright && npx playwright test && cd -)
